FROM ubuntu:24.04

ENV HADOOP_VERSION=3.3.6
ENV SPARK_VERSION=3.5.3
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_HOME=/opt/hadoop
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$SPARK_HOME/bin

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget openssh-server curl bash && \
    wget https://dlcdn.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
    tar -xzf hadoop-${HADOOP_VERSION}.tar.gz && \
    mv hadoop-${HADOOP_VERSION} /opt/hadoop && \
    wget https://dlcdn.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz && \
    tar -xzf spark-${SPARK_VERSION}-bin-hadoop3.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop3 /opt/spark && \
    rm hadoop-${HADOOP_VERSION}.tar.gz spark-${SPARK_VERSION}-bin-hadoop3.tgz

# Set bash as the default shell
SHELL ["/bin/bash", "-c"]

# Set appropriate ownership of Hadoop directories
RUN chown -R hdfs:hdfs /opt/hadoop && \
    chown -R yarn:yarn /opt/hadoop

# Generate SSH key and configure SSH
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys && \
    echo "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config

# Expose necessary ports and continue with your existing setup
EXPOSE 9870 8088 7077 8080 22

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]